services:
  postgres:
    image: postgres:16
    container_name: jobservice_postgres
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpass
    ports:
      - "5432:5432"
    volumes:
      - jobservice_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jobservice_redis
    ports:
      - "6379:6379"

volumes:
  jobservice_pgdata: